on:
  push:
    tags: "*"

jobs:
  push_to_dockerhub:
    strategy:
      matrix:
        image:
          - {folder: gp2gp-translator, dockerhub_name: nia-ps-adaptor}
          - {folder: gpc-facade, dockerhub_name: nia-ps-facade}
          - {folder: db-migration, dockerhub_name: nia-ps-db-migration}
          - {folder: snomed-schema, dockerhub_name: nia-ps-snomed-schema}
    uses: azam145/nia-patient-switching-standard-adaptor/.github/workflows/common.yml@main
    with:
        dockerhub_name: ${{matrix.image.dockerhub_name}}
        folder: ${{matrix.image.folder}}
    secrets: inherit